name: scp files

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.head_ref }}
      
    - name: Set target directory for main branch
      if: (github.ref == 'refs/heads/main') || (github.event.pull_request.base.ref == 'main')
      run: echo "TARGET_DIR=./web/zari/zari.xiyo.dev" >> $GITHUB_ENV

    - name: Set target directory for develop branch
      if: (github.ref == 'refs/heads/develop') || (github.event.pull_request.base.ref == 'develop')
      run: echo "TARGET_DIR=./web/zari/zari-dev.xiyo.dev" >> $GITHUB_ENV

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USER }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        port: ${{ secrets.DEPLOY_SERVER_PORT }}
        source: "./"
        target: ${{ env.TARGET_DIR }}
